### ISSUE TITLE
채널 기능 구현

### ISSUE THREAD

**Issue by k0duck** [CHZZK-Study/team-1-server#2]
## ✨ 구현 기능

채널의 기본적인 CRUD를 구현합니다.

## ✅ TODO

- [x] 채널 엔티티 생성
- [x] 채널 생성 기능 구현
- [x] 채널 삭제 기능 구현
- [x] 채널 목록 조회 기능 구현
- [x] 채널 수정 기능 구현
