### ISSUE TITLE
그룹 기본 기능 구현

### ISSUE THREAD

**Issue by junslog** [CHZZK-Study/team-1-server#3]
## ✨ 구현 기능

그룹 관련 기본 CRUD 기능을 작성합니다.

## ✅ TODO

- [x] 그룹 생성 기능
- [ ] 그룹 삭제 기능
- [ ] 그룹 수정 기능
